version: "3"
services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_DB: competitions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
